project:
  type: website

website:
  title: "assignment-3-ecm244"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about_me.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



